# comments starts with `#'

# flags used to create nob modules.
nob-dl-flags=-shared, -rdynamic, -fPIC

# directory to store all object files, libraries, and executables.
build-dir=./build

# path to the C compiler.
c-compiler=/bin/gcc

# warnings flags for C.
c-warnings=-Wall, -Werror, -pedantic, -pedantic-errors

# flags for debug builds.
c-debug-flags=-g


c3-compiler=/bin/c3c

c3-warnings-flags=

# util to create static lib.
# will be used as
#
# <archive> <archive-flags> build/name/libname.a build/name/obj1.o ... 
archive=ar

# flags for archive util.
archive-flags=rs
